client_id = "f26399e21b46d87b1c49777e4118c35e"
name = "Artist Ledger"
application_url = "https://artist-ledger.shdw-gallery.workers.dev"
embedded = true

[access_scopes]
scopes = "read_products,read_inventory,read_orders"
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://artist-ledger.shdw-gallery.workers.dev/auth/callback"]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks/privacy"
