CREATE TABLE IF NOT EXISTS GmailConnection (shop TEXT PRIMARY KEY, email TEXT NOT NULL, token TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS GmailOAuth (state TEXT PRIMARY KEY, shop TEXT NOT NULL, expires INTEGER NOT NULL, browser TEXT, verifier TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS GmailDelivery (id TEXT PRIMARY KEY, shop TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'sending');
